### ISSUE TITLE
VICE test drive/skew.prg fails in 1.0.9.9

### ISSUE THREAD

**Issue by dirkwhoffmann** [davidhorrocks/hoxs64#2]
![screenshot 2018-08-12 12 59 19](https://user-images.githubusercontent.com/12561945/44001407-d4d92c16-9e31-11e8-9f22-dc30d7d1598d.png)

To reproduce, use skew.D64, not skew.G64 which runs fine. 

I came across this when I tried to get this test passed by VirtualC64. I observed that it passed in VirtualC64 when I used the Hoxs64 tail gap values in my disk encoder. Formerly, I used tailgaps 9,9,9,9 (for the four speed zones) which I extracted from a G64 image created with 64COPY (https://github.com/dirkwhoffmann/virtualc64/issues/384).

As the screenshot shows, Hoxs64 is showing an error in every second line, so it might have something to do with the handling of halftracks.

**Comment by davidhorrocks** [comment]
Hi Dirk,
As you know, the skew test is testing for aligned tracks. However, Hoxs64 loads D64 files with unaligned tracks using a fixed arbitrary skew by default. This arbitrary skew causes the skew test to fail. You have to select “Align Tracks” in the Hoxs64 file browser to make this test pass.

**Comment by dirkwhoffmann** [comment]
Hi David,
thanks for the explanation! I missed to check for the alignment option.
