### ISSUE TITLE
[Feature request] Please add a Portable/standalone mode

### ISSUE THREAD

**Issue by IronYoshi64** [davidhorrocks/hoxs64#3]
Hey! I love this C64 emulator because its easy to use and it plays most games I have very well! I like it a lot! I have a feature request.

I would love if you can add some sort of a Portable/Standalone mode for all of its settings and configurations. Right now it uses the Windows Registry (HKEY_CURRENT_USER\Software\Hoxs64\) for all of its settings. I really wish that this emulator did not write to the registry, and instead wrote its Settings to a file or files like "hoxs64.ini", or "hoxs64.xml", or something. Or maybe add a command-line option like -portable, or upon loading Hoxs64, it looks for a portable.txt file or something, like how Dolphin is. Or maybe add a portable build download or so.

I think this would be a great feature to add for people like me that prefers to have everything easily accessible and easy to backup its configurations, etc.

**Comment by davidhorrocks** [comment]
Portable setting are now implemented in a new version 1.1.2.1 which includes menu and command line options to save and load setting from an INI file. This new version requires key assignments to be explicitly specified. Default key assigned are configured only if no saved settings are found.

The order of precedence is:
1 Command line option -configfile <filename>
2 A hoxs64.ini settings file in the application folder.
3 The registry settings in HKEY_CURRENT_USER\Software\Hoxs64
4 Defaults
