### ISSUE TITLE
CRT Hardware ID 15 (C64Game System / System 3)

### ISSUE THREAD

**Issue by commodroid** [davidhorrocks/hoxs64#4]
Dear David,

Your System 3 cartridge handler crashes with "Commodore 64 Game System (1990)(Commodore).crt".
Only Fiendish Freddy's Big Top O'Fun works from it.
International Soccer, Flimbo's Quest and Klax causes a "RUNSTOP+RESTORE like" situation.
This type of cartridges do bankswitching on read access too, not just on write accesses.
If you copy your code from CartSystem3::WriteRegister(.....) into CartSystem3::ReadRegister(.....), it will work perfectly.
And the "if (address >= 0xDE00 || address < 0xDF00)" has a typo, the '||' may be '&&'.

Sincerely,
Lorant

**Comment by davidhorrocks** [comment]
Nice find. I will get this fixed in the source ASAP.

**Comment by davidhorrocks** [comment]
Fixed in master. Awaiting the next release.

**Comment by davidhorrocks** [comment]
Fixed in v1.1.0.5+
